---
- name: Setup Dev Environment
  hosts: localhost
  become: yes

  vars:
    ssh_dir: "~/.ssh"

  tasks:
    # Update and upgrade system
    - name: Update system
      apt:
        update_cache: yes
        upgrade: dist

    # Install essential packages
    - name: Install essential tools
      apt: 
        name: 
          - git
          - stow
          - zsh
          - tmux
          - xclip
          - eza
          - curl
          - bat
          - gcc
          - clang
          - build-essential
          - libstdc++-12-dev
        state: present

    # Install Neovim from github repository
    - name: download neovim binary
      get_url:
        url: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
        dest: "/tmp/nvim-linux64.tar.gz"

    - name: remove old nvim version
      file:
        path: "/opt/nvim"
        state: absent

    - name: extract neovim binary to /opt
      unarchive:
        src: "/tmp/nvim-linux64.tar.gz"
        dest: "/opt"
        remote_src: yes
    - name: symlink neovim binary to /usr/bin
      file:
        src: "/opt/nvim-linux64/bin/nvim"
        dest: "/usr/bin/nvim"
        state: link

    - name: "clean downloaded file"
      file:
        path: "/tmp/nvim-linux64.tar.gz"
        state: absent

    # ensure /root/.ssh directory exists
    - name: ensure /root/.ssh directory exists
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'

    # deploy ssh private keys
    - name: deploy ssh private keys
      copy:
        src: "ssh/{{item}}"
        dest: "{{ ssh_dir }}/{{ item | regex_replace('.enc$', '') }}"
        mode: '0600'
        decrypt: yes
      with_items:
        - id_ed25519_personal.enc
        - id_ed25519_heyday.enc
        - id_ed25519_work.enc

    # Deploy SSH public keys
    - name: Deploy SSH public keys
      copy:
        src: "ssh/{{item}}"
        dest: "{{ ssh_dir }}/{{item}}"
        mode: '0644'
      with_items:
        - id_ed25519_personal.pub
        - id_ed25519_work.pub
        - id_ed25519_heyday.pub
    
    # Set up SSH config
    - name: Deploy SSH Config
      copy:
        src: "ssh/config"
        dest: "{{ ssh_dir }}/config"
        mode: '0644'

    # Add Github to known_hosts
    - name: Add GitHub to known_hosts
      known_hosts:
        path: "~/.ssh/known_hosts"
        name: "github.com"
        key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"

    # Clone dotfiles repository
    - name: Clone dotfiles repository
      git: 
        repo: git@github-personal:DavidRozner/dotfiles.git
        dest: ~/dotfiles
        key_file: "~/.ssh/id_ed25519_personal"
        version: HEAD

    # Use Stow for symlink dotfiles
    - name: Apply dotfiles using Stow
      shell: |
        stow zsh
        stow nvim
        stow tmux
        stow git
        stow ideavim
      args:
        chdir: ~/dotfiles

