---
- name: Setup Dev Environment
  hosts: localhost
  become: false

  vars:
    home_dir: "{{ ansible_env.HOME }}"
    ssh_dir: "{{ home_dir }}/.ssh"

  roles:
    - role: system
    - role: zsh
    - role: nvim
    - role: ssh
    - role: tmux
    - role: dotfiles
    - role: fonts
    - role: lsp

  tasks:
