---
- name: Update system
  become: true
  apt:
    update_cache: yes
    upgrade: dist
  ignore_errors: yes

- name: Install essential tools
  become: true
  apt:
      name:
      - git
      - stow
      - zsh
      - tmux
      - xclip
      - eza
      - unzip
      - curl
      - bat
      - gcc
      - clang
      - procps
      - build-essential
      - libstdc++-12-dev
      - wget
      - fzf
      state: present
  tags:
      - essential
